version: '3.9'

services:

  postgresForMonitoringDockerContainer:
    image: postgres:15
    container_name: postgresForMonitoringDockerContainer
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: durka
      POSTGRES_DB: monitoring-docker-container
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pinger-network


  backend:
    build:
      context: ./backend-service
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - postgresForMonitoringDockerContainer
    environment:
      - DB_URL=postgres://postgres:durka@postgresForMonitoringDockerContainer:5432/monitoring-docker-container?sslmode=disable
      - CONFIG_PATH=config/config.yaml
    networks:
      - pinger-network

  frontend:
    build:
      context: ./frontend-service/frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - frontend-server
      - postgresForMonitoringDockerContainer
      - backend
    #environment:
    networks:
      - pinger-network

  frontend-server:
    build:
      context: ./frontend-service/server
      dockerfile: Dockerfile
    container_name: frontend-server
    ports:
      - "3001:3001"
    depends_on:
      - postgresForMonitoringDockerContainer
      - backend
    networks:
      - pinger-network

  pinger:
    build:
      context: ./pinger-service
      dockerfile: Dockerfile
    container_name: pinger
    cap_add:
      - NET_RAW
      - NET_ADMIN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CONFIG_PATH=config/config.yaml
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DOCKER_API_VERSION=1.45
    depends_on:
      - frontend
      - frontend-server
      - postgresForMonitoringDockerContainer
      - backend
    networks: 
      - pinger-network

volumes:
  postgres_data:

networks:
  pinger-network:
    driver: bridge
    external: true
      
